# Minimal pre-commit hooks for org-wide standards
# Source: org-standards (simplified from fashion-extract)
#
# Projects can add custom hooks by creating .pre-commit-config-custom.yaml

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  # Ruff - replaces black, isort, flake8
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: 3.0.0
